### ISSUE TITLE
Ontology Portal support team references recipient@example.org

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/Semantic-Portal#3]
Upon successful submission of a new ontology, the email address referencing support is incorrect, it needs to be updated to resolve to actual support instead of recipient@example.org
<img width="1440" alt="screen shot 2017-04-11 at 6 40 30 pm" src="https://cloud.githubusercontent.com/assets/1165719/24937584/82042ff2-1ee6-11e7-8abe-9a3d4b3a6ab4.png">

**Comment by linepouchard** [comment]
The URL for the ontology is valid.  The address for the response team is not.  After fixing the address above, the portal instance needs to be re-started.  This will point to a new IP address, that is no longer referenced under http://semanticportal.esipfed.org.  Until this issue is fixed within ECITE, this example address will appear.

**Comment by linepouchard** [comment]
Fixed
